Repository Azure/communication-ui-library-ios, pull requests merged in 2022-11, with the labels that each got.

#417 [Bug] Pass AAD token in UIKit demo view
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
Labels: bug

#428 [Refactor] Call id string constans refactor
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/DiagnosticsSharingActivityViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/StringConstants.swift
Labels: refactor

#415 [Feature] Send read receipt presentation layer
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/StringExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
Labels: feature, task

#423 [Bugfix] Work around for failure to grab ownership of microphone on first try.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AudioSessionManager.swift
Labels: bug

#426 [Feature] Implement Telemetry for chat
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
Labels: task

#430 [Task] Added logging for diagnostics info in demo apps
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
Labels: task

#433 [Task] Update Version to 1.1.0
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
Labels: task

#438 [Task] Update podspec for 1.1.0 GA
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: task

#416 [Doc] Update CHANGELOG.md and README.md for 1.1.0 release
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  README.md
Labels: documentation, task

#435 [Task] Update calling sdk version in manual installation guide
  docs/manual-installation.md
Labels: documentation, task

#421 [Task] chat typing clear logic update
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/UserEventTimestampModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/FluentUI/Wrapper/TypingParticipantAvatarGroup.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/FluentUI/Wrapper/TypingParticipantAvatarGroupContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ParticipantsState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ParticipantsReducerTests.swift
Labels: task

#445 [Bug] Update the paths for shared source
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
Labels: refactor

#425 [Task] Create custom scrolling view and update icon sizing for Chat
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_arrow_down_24_filled.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_arrow_down_24_filled.imageset/ic_fluent_arrow_down_24_filled.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/ObservableScrollView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/RepositoryState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/RepositoryReducerTests.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/FluentUI/Wrapper/CompositeButton.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/PrimaryButton.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/PrimaryButtonViewModel.swift
Labels: task

#441 [Feature] Implemented service/redux layer for chat participants
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TopBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatSDKAsyncExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ParticipantsReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#439 [Feature] added script to update version
  scripts/README.md
  scripts/main-repo-updater.py
Labels: feature

#456 [Doc] Fix Github Link
  scripts/README.md
Labels: documentation

#457 [Bugfix] Resolved presentation bugs
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_person_add_24_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_person_add_24_regular.imageset/person-add.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_person_remove_24_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_person_remove_24_regular.imageset/person-arrow-left.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_ios_arrow_left_24_filled.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_ios_arrow_left_24_filled.imageset/ic_fluent_ios_arrow_ltr_24_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsView.swift
Labels: task

#455 [Feature] Implemented service layer and redux layer for editing/deleting message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/RepositoryAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#452 [Task] Add Basic Error Handling
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CredentialsView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ErrorReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#450 [Task] Handling Local User Removed
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ParticipantInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ParticipantsInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatParticipantExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
Labels: task

#448 [Feature] Redux layer and Presentation layer for receive read receipt
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_eye_12_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_eye_12_regular.imageset/ic_fluent_eye_12_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ParticipantsState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ParticipantsReducerTests.swift
Labels: feature

#458 [Refactor] Refactor and renaming of public api for chat
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatCompositeOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/DiagnosticConfig.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/LocalizationOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/RemoteOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/SetParticipantViewDataError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/ChatCompositeView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/ErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Navigation/NavigationRouter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/ChatCompositeViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/ChatCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/ErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ErrorReducerTests.swift
Labels: task

#464 [Bugfix] Fix for Share diagnostics label is clipped in A11y Font Sizes
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/MoreCallOptionsListCell.swift
Labels: bug

#468 [Bugfix] Fixed share diagnostics info UITest for iPad
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppCallTests.swift
Labels: bug

#462 [Feature] Mask admin user from read receipt and participant added message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatThreadInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ParticipantsState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ParticipantsReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: feature

#411 [Feature] Created mock up model for CallingSDKWrapper and integrate mock in basic UI test
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallClientMockings.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallConfigurationMocking.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Utilities/AccessibilityId.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependencyContainer.swift
Labels: feature

#470 [Bugfix] Chat bug fixes for layout, skip messages button, keyboard, and message input
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Utilities/UIApplicationHelper.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/FluentUI/Wrapper/CompositeButton.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/PrimaryButton.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/PrimaryButtonViewModel.swift
Labels: bug

#465 [Refactor] Clean up public api and unused error codes
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/ChatCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/ErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ErrorReducerTests.swift
Labels: task

#473 [Refactor] Refactoring isLocalUser for ChatMessageInfoModel
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/LocalUserInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatMessageExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
Labels: refactor

#474 [Feature] Chat parse Teams html RichText message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatMessageExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/StringExtension.swift
Labels: task

#451 [Refactor] Introduce a new sharable drawer list view model
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/AudioDevicesListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeAudioDevicesList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeAudioDevicesListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/MoreCallOptionsList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/MoreCallOptionsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/MoreCallOptionsListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/AudioDevicesListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/AudioDevicesListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/DrawerListItemViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/LeaveCallConfirmationViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/MoreCallOptionsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/MoreCallOptionsListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
Labels: refactor

#477 [Bugfix] Layout fix for CallingView
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
Labels: bug

#481 [Refactor] RemoteParticipantsManager update
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/RemoteParticipantsManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/RemoteParticipantExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/Extension/CommunicationIdentifierExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingSDKWrapperMocking.swift
Labels: refactor

#483 [Bugfix] Fix new thread mask admin user crash
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
Labels: bug

#484 [Feature] Localization support for 6 additional languages
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ar.lproj/LaunchScreen.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ar.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalizationOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he-IL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pl-PL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv-SE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv.lproj/Localizable.strings
Labels: feature

#469 [Feature] Filter trouter event for current threadId only
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatEventModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatSDKEventsHandlerTests.swift
Labels: task

#471 [Bugfix] Hide setup control bar while joining call when video is on
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
Labels: bug

#476 [Refactor] Renamed CallDiagnostics to DebugInfo
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DebugInfo.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DiagnosticConfig.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/DebugInfoManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/MoreCallOptionsListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/DebugInfoSharingActivityViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/DiagnosticsSharingActivityViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/SharingActivityContainerController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/SharingActivityView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/DebugInfoManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/DiagnosticsManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/StringConstants.swift
Labels: refactor

#485 [Bugfix] Fix for disabled switch camera button tap gesture handling
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
Labels: bug

#486 [Bugfix] Fixed the archiving issue introduced by using @testable import in demo app
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/AppConfig.xcconfig
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallConfigurationMocking.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
Labels: bug

#480 [Refactor][Bugfix] Refactor messages to no longer use viewmodels and move refactor read Icon logic
  AzureCommunicationUI/Podfile.lock
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/HtmlMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/HtmlMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ViewModels/MessageViewModelMocking.swift
Labels: bug
