Repository Azure/communication-ui-library-ios, pull requests merged in 2022-12, with the labels that each got.

#492 [Task] Display html msg for Teams messages
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
Labels: task

#497 [Bug] Fix Theming Override Not Working
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
Labels: bug

#494 [Refactor] Clarify dependency construction for chat library
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/ChatCompositeView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/ChatCompositeViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Redux/Store.swift
Labels: refactor

#490 [Task] Send read receipt when scrolling ends
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
Labels: task

#500 [Bugfix] Fix adding duplicate messages to message repository
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
Labels: bug

#499 [Bugfix] Remove scroll indicator and send button fixes
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_send_24_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_send_24_regular.imageset/ic_fluent_send_24_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/StringExtension.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
Labels: bug

#504 [Bug] Demo App Needs Rotation Disabled
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/AppDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
Labels: bug

#505 [Bugfix] Documentation Update for manual install on prior to iOS 14
  docs/manual-installation.md
Labels: documentation

#489 [Task] Add Alert to Demo App
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ViewModifier/ErrorView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ErrorReducerTests.swift
Labels: task

#506 [Feature] Implement message send status (Sending, delivered, failed)
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_checkmark_circle_12_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_checkmark_circle_12_regular.imageset/ic_fluent_checkmark_circle_12_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_circle_12_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_circle_12_regular.imageset/ic_fluent_circle_12_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_error_circle_12_regular.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_error_circle_12_regular.imageset/ic_fluent_error_circle_12_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/RepositoryAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
Labels: feature

#491 [Doc] Readme Update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/manual-installation.md
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
  README.md
  docs/images/calling.png
  docs/images/chat.png
  docs/images/mobile-ui-library-calling-hero-image.png
  docs/images/mobile-ui-library-chat-hero-image.png
  docs/images/mobile-ui-library-hero-image.png
Labels: documentation

#512 [Task] Back merge develop to feature/chat
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Store.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/CallCompositeTests.swift
  eng/pipelines/ci.yml
Labels: task

#518 [Documentation] 1.2.0-beta.1 versions update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
Labels: documentation

#514 [Bugfix] Fix permission label clipped in large font sizes
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
Labels: bug

#508 [Feature] Introduce the Chat podspec
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
Labels: feature

#529 [Documentation] Podspec update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: documentation

#513 [Refactor] Move threadId out from ChatConfiguration
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Redux/Store.swift
Labels: task

#530 [Task] Merge Develop to Feature/chat
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DebugInfo.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/DebugInfoSharingActivityViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/manual-installation.md
  eng/pipelines/ci.yml
  eng/pipelines/jobs/CI-build-job.yml
  eng/pipelines/jobs/UI-test-job.yml
  eng/pipelines/jobs/templates/build-and-coverage.yml
  eng/pipelines/jobs/templates/retrieve-acs-token.yml
  eng/pipelines/nightly.yml
Labels: task

#493 [Bugfix] Fix progress label for join call button
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he-IL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv-SE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr.lproj/Localizable.strings
  eng/pipelines/jobs/CI-build-job.yml
Labels: bug

#540 [Config] Removed swiftPM files
  AzureCommunicationUI/AzureCommunicationUIChat/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Labels: config

#539 [Bug] Fixed New Message Button Being Triggered By System Message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
Labels: bug

#543 [Feature] Calling SDK e2e test mocking enabler
  AzureCommunicationUI/AzureCommunicationUI.xcworkspace/contents.xcworkspacedata
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/xcshareddata/xcschemes/AzureCommunicationUIDemoApp.xcscheme
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/FloatingUITestWindow.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppDebugInfoTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppTokenTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift
  AzureCommunicationUI/Podfile.lock
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/AccessibilityIdentifier.swift
Labels: feature

#534 [Task] Add red background color to failed messages
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
Labels: task

#542 [Bugfix] Fix placeholder text view blocks TextEditor
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
Labels: bug

#537 [Doc] Updated Release Note For Chat
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
Labels: documentation, task

#550 [Bug] Scroll to Bottom When Keyboard Shows Up
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/Utilities/ViewExtension.swift
Labels: bug

#547 [Bug] Added Default Display Name
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatParticipantExtension.swift
Labels: bug

#548 [Bugfix] Resolve issue with date header and text input box cursor padding
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
Labels: bug

#551 [Refactor] Added Documentation to Public Functions and Refactored LocalOptions
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/ChatCompositeView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/ChatCompositeViewController.swift
  AzureCommunicationUI/sdk/common/Chat/Sources/CompositeOptions/LocalOptions.swift
Labels: documentation, refactor

#549 [Feature] Disconnect public api stops the real time notifications
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/CompositeManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
Labels: feature

#555 [Feature][Refactor] Migrate AppCenter test pipeline to YAML
  eng/pipelines/jobs/UI-test-job.yml
  eng/pipelines/jobs/appcenter-test-job-steps.yml
  eng/pipelines/jobs/templates/configure-for-enterprise-signing.yml
  eng/pipelines/jobs/templates/retrieve-acs-token.yml
  eng/pipelines/jobs/templates/run-appcenter-test.yml
  eng/pipelines/jobs/templates/set-appcenter-devices.yml
  eng/pipelines/jobs/templates/update-demo-app-plist-for-testing.yml
  eng/pipelines/nightly.yml
Labels: feature

#557 [Doc] Removed References of Teams Interop
  README.md
Labels: documentation

#558 [Feature] Improve pipeline performance
  eng/pipelines/nightly.yml
Labels: feature

#553 [Bugfix] Trim any white space and new line characters before and after the message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/StringExtension.swift
Labels: bug

#561 [Documentation] Updating the chat readme quick samples
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
Labels: documentation

#564 [Refactor] Update ChatAdapter init to align with Android API
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
Labels: refactor

#556 [Bugfix] Resolve the chat view still stays on screen even after chat has been stopped on iPad.
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
Labels: bug

#554 [Bugfix] Fix scrolling and fetch issues.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/AudioDevicesListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/MoreCallOptionsListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/RepositoryState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatMessageExtension.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/Utilities/ViewExtension.swift
Labels: bug
