Repository Azure/communication-ui-library-ios, pull requests merged in 2022-06, with the labels that each got.

#226 [Refactor] Rename LocalSettings to LocalOptions
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/LocalOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantsListViewModelTests.swift
Labels: refactor

#224 [Bugfix] Prevented the pip view from being repositioned when the there is already overlay / drawer displayed on the screen.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
Labels: bug

#212 [Refactor] Introduce new error event completion handler
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeErrorEvent.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/LocalOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/SetParticipantViewDataError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
Labels: refactor

#228 [Bugfix] Add speaking indication to voiceover for participant grid.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/LocalizationKey.swift
Labels: bug

#222 [Bug] Fix the composite thrown error code when user failed to resume
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LobbyOverlayView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/CallingSDKEventsHandler.swift
Labels: bug

#221 [Feature] multiple UX update iPad
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/DraggableLocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Container/ContainerView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Utilities/EnvironmentValuesExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Utilities/OrientationManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/ArrayExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/ViewModels/ParticipantGridViewModelMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantGridsViewModelTests.swift
Labels: feature

#227 [Refactor] Update set events functions
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/RemoteParticipantsManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/RemoteParticipantsManagerTests.swift
Labels: refactor

#230 [Documentation] Documentation update for AzureCommunicationUICalling 1.0.0-beta.2
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CallCompositeOptions/DiagnosticConfigTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  README.md
Labels: documentation

#233 [Refactor] Update Swift version in podspec
  AzureCommunicationUI/sdk/AzureCommunicationUI.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: refactor

#237 [Refactor] TD translation
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/es-ES.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ja-JP.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hans-CN.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hant-TW.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh.lproj/Localizable.strings
Labels: refactor

#236 [Bugfix] fixed one retain cycle of call composite
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
Labels: bug

#238 [BugFix] Fix the issue that local video status is inconsistent after call resume from background
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/LocalUserReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/LocalUserReducerTests.swift
Labels: bug

#242 [Bugfix] Remove deleting localVideoStreamIdentifier when video is paused
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/LocalUserReducer.swift
Labels: bug

#247 [Bugfix] Show info header with keyboard
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AccessibilityProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Utilities/AccessibilityProviderNotificationsObserver.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/AccessibilityProviderMocking.swift
Labels: bug

#248 [Documentation] SUPPORT.md update
  SUPPORT.md
Labels: documentation

#245 [Refactor] Added unit test for call on hold feature
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/ViewModels/OnHoldOverlayViewModelMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/OnHoldOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/AudioSessionReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Service/CallingServiceTests.swift
Labels: refactor, task

#251 [Refactor] Renaming CallCompositeLocator to JoinLocator
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallConfiguration.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/RemoteOptions.swift
Labels: refactor

#257 [Documentation] Changelog date update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: documentation

#249 [Refactor] Separate CallCompositeError with internal error code
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Model/CallInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/CallingAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandlerExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/CallingSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/Extension/ACSCallEndReasonExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/CallCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/CompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/AppStateReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
Labels: refactor

#262 [Bug] Accessibility hold overlay should be solid colour
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Assets.xcassets/Color/onHoldBackground.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LobbyOverlayView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/OnHoldOverlayViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/OverlayViewModelProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/ColorExtension.swift
Labels: bug

#263 [Refactor] Dependency upgrade for CallingSDK
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/CallingSDKWrapper.swift
Labels: refactor

#259 [Bugfix] Resolved issue where call on hold error notification did not announce with voice over when displaying on screen.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LobbyOverlayView.swift
Labels: bug

#255 [Refactor ] Updated the item arrangement of the control bar view on iPhone layout
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
Labels: refactor

#267 [Documentation] CHANGELOG update
  AzureCommunicationUI/sdk/AzureCommunicationUI.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUI/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#266 [Bug] Remove mute icon when the remote participant is on hold
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
Labels: bug

#269 [Bugfix] Fix compliance banner offset
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
Labels: bug

#258 [Bugfix] Add one fix for testLaunch() failure in AppCenter by removing the unneeded testLaunch function
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
Labels: bug

#254 [Refactor] Make scripts of running SwiftLint optional
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  docs/manual-installation.md
Labels: refactor

#265 [Refactor] Added basic uitests for setup view
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppSetupViewTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/AccessibilityIdentifier.swift
Labels: refactor

#268 [Bug] Fix the issue that resume a call without internet would stop user from exit
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: bug

#270 [Refactor] Add delay for camera status update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  CHANGELOG.md
Labels: refactor

#271 [Documentation] Project version bump to GA
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CallCompositeOptions/DiagnosticConfigTests.swift
  README.md
Labels: documentation

#272 [Bugfix] CallingMiddlewareHandlerTests fix
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
Labels: bug

#273 [Bugfix] Not trigger CameraPreviewOnTriggered when have internal error
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: bug

#250 [Refactor] Video view bridging to SwiftUI update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/VideoRenderView.swift
Labels: refactor

#280 [Bugfix] Demo app can't dismiss setting page when in landscape mode (#2899277)
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
Labels: bug

#281 [Bug] Fixing speaking overly custom color
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
Labels: bug

#284 [Refactor] Unit tests retain cycle fix
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CallCompositeOptions/DiagnosticConfigTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/ViewModels/ParticipantGridCellViewModelMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/BannerInfoTypeTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/BannerTextViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/BannerViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/LobbyOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/OnHoldOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantCellViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantGridsViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantsListViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Provider/LocalizationProviderTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/JoiningCallActivityViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/SetupViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/ViewComponents/AudioDevicesListViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/ViewComponents/LocalVideoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/LifeCycleReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Service/CallingServiceTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Service/NavigationRouterTests.swift
Labels: refactor
