Repository Azure/communication-ui-library-ios, pull requests merged in 2022-05, with the labels that each got.

#147 [Refactor] ZoomableVideoRenderView optimization and refactoring
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
Labels: refactor

#148 [Feature] Add an event for notifying when participants joined a call
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeEventsHandler.swift
  AzureCommunicationUI/AzureCommunicationUI/DI/DependancyContainer.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/RemoteParticipantsManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Service/Calling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/CompositeRemoteParticipantsManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/CallingSDKWrapperMocking.swift
Labels: task

#151 [Feature] Draggable PiP
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/ViewExtension.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/ViewModifer.swift
Labels: feature

#155 [Refactor] Extract accessibility id out of LocalizationKey
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/AccessibilityIdentifier.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Utilities/AccessibilityId.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/ViewModifier/TextFieldClearButton.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
Labels: refactor

#153 [Refactor] Refactored call eviction error handling not to be propagated to contoso
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/CompositeErrorManager.swift
Labels: refactor

#154 [Feature] Add functionality for setting remote participant persona data
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CommunicationULocalDataOptions.swift
  AzureCommunicationUI/AzureCommunicationUI/DI/DependancyContainer.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/CompositeError.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/CompositeRemoteParticipantsManagerTests.swift
Labels: task

#156 [Bugfix] Add mute status for accessibility label on participant grid.
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridCellViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantCellViewModelTests.swift
Labels: bug

#159 [Documentation] Update ChangeLog for Theming and Draggable Pip
  CHANGELOG.md
Labels: documentation

#157 [Bugfix] Accessibility VoiceOver for screen share and join call
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridCellViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantCellViewModelTests.swift
Labels: bug

#158 [Refactor] Change LanguageCode string enum to CommunicationUISupportedLocale with Locale static variables
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Provider/LocalizationProviderTests.swift
  CHANGELOG.md
Labels: refactor

#166 [Refactor] Update PersonaData argument name
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationULocalDataOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
Labels: refactor

#164 [Bugfix] Limit text size for icon label buttons
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Utilities/FontExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
Labels: bug

#169 [Bugfix] Accessibility drawer text size
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
Labels: bug

#172 [Documentation] readme and docs update
  AzureCommunicationUI/AzureCommunicationUIDemoApp/README.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CallCompositeOptions/DiagnosticConfigTests.swift
  README.md
  docs/contributing-guide.md
  docs/manual-installation.md
Labels: documentation

#173 [Refactor] TD build for translation
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/es-ES.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ja-JP.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hans-CN.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hant-TW.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh.lproj/Localizable.strings
Labels: refactor

#171 [Feature] Display remote participants persona data in the grid view
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Factories/CompositeViewFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
Labels: task

#175 [Feature] Display version and build number in demo app entry view
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/EntryViewController.swift
Labels: feature

#176 [Bugfix] PiP RTL(Right to Left) solution for reversing the drag coordinates
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
Labels: bug

#181 [Refactor] Update PersonaData to new name
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationULocalDataOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/LocalSettings.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Factories/CompositeViewFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
Labels: refactor

#174 [Feature] Change how we set event handler
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  CHANGELOG.md
Labels: feature

#180 [Bugfix] Reset position when rotating and drawer is open
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
Labels: bug

#187 [Refactor] AvatarManagerTest no longer load UIImage
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
Labels: refactor

#190 [Feature] Strings for call on hold
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/LocalizationKey.swift
Labels: task

#192 [Refactor] Import UIKit inside FluentUI wrapper
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/AudioDevicesListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeAudioDevicesList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeAudioDevicesListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeButton.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeParticipantsList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Style/IconProvider.swift
Labels: refactor

#188 [Documentation] Updated the CHANGELOG for the 1.0.0 beta 1 release
  AzureCommunicationUI/AzureCommunicationUIDemoApp/README.md
  AzureCommunicationUI/sdk/AzureCommunicationUI/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  CHANGELOG.md
Labels: task

#204 [Feature] Implement call denied behaviour to return to setup view
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/Extension/ACSCallEndReasonExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
Labels: feature

#205 [Feature] Error handling for participants view data
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/NavigationState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Store.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Utilities/CompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/AvatarViewManagerMocking.swift
Labels: task

#207 [Refactor] TD Build translation for localization strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/es-ES.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ja-JP.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hans-CN.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hant-TW.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Localization/zh.lproj/Localizable.strings
Labels: refactor

#209 [Feature] Custom Data Model injection feature
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Factories/CompositeViewFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeParticipantsList.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/RemoteParticipantsManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/NavigationState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Store.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/AvatarViewManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/CallingSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantsListViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: feature

#177 [Feature] Reposition and reduced the width of the participation banner in iPad layout in calling view.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
Labels: feature

#191 [Feature] Updated setup screen UX on iPad
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupView.swift
Labels: feature

#211 [Refactor] Move managers setup to DependencyContainer
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/DI/DependencyContainerTests.swift
Labels: refactor

#219 [Feature] Remove the interruption end handling
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CallingMiddlewareHandlerMocking.swift
Labels: task

#215 [Refactor] Renaming configurations to options
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/ThemeConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/LocalizationOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/ThemeOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Style/StyleProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/LocalizationProviderMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Provider/LocalizationProviderTests.swift
Labels: refactor

#214 [Refactor] Change supported locales to function under supported locale struct
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/LocalizationOptions.swift
Labels: refactor

#216 [Refactor] Prefix renaming for CommunicationUI- to CallComposite-
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CallCompositeErrorEvent.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/LocalizationOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/CallingAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandlerExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Provider/LocalizationProviderTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/AppStateReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
Labels: refactor

#203 [Feature] Updated participant grid layout for iPad
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Utilities/EnvironmentValuesExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Utilities/OrientationManager.swift
Labels: feature

#213 [Feature] Call On Hold Error Code Update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddlewareHandler.swift
Labels: task

#218 [Feature] Add onHold state for remote participant with UI/UX update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Model/ParticipantInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/Extension/ACSCallingStateExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/Extension/ACSParticipantStateExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/Extension/RemoteParticipantExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Service/Calling/RemoteParticipantsEventsAdapter.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Builder/ParticipantInfoModelBuilder.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ParticipantsListViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/AppStateReducerTests.swift
Labels: task

#210 [Feature] Call On Hold View
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Assets.xcassets/Color/ACSPrimaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/FluentUI/Wrapper/CompositeButton.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/LobbyOverlayView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/LobbyOverlayViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LobbyOverlayView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LobbyOverlayViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/OnHoldOverlayViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/OverlayViewModelProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Mocking/ViewModels/ControlBarViewModelMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Calling/LobbyOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Presentation/Setup/ErrorInfoViewModelTests.swift
Labels: task
