Repository Azure/communication-ui-library-ios, pull requests merged in 2022-03, with the labels that each got.

#55 [Refactor] Add unit tests for SetupViewModel, PreviewAreaViewModel and SetupControlBarViewModel
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/AudioDeviceListViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ErrorInfoViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/IconWithLabelButtonViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/PreviewAreaViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/PrimaryButtonViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/SetupControlBarViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupViewModelTests.swift
Labels: refactor

#58 [Feature] Disable the setup control buttons in Join Experience
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/SetupControlBarViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupViewModelTests.swift
Labels: feature

#62 [Refactor] Convert LocalizationProvider to protocol
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/DI/DependancyContainer.swift
  AzureCommunicationUI/AzureCommunicationUI/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/StringKeys.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/LocalizationProviderMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Provider/LocalizationProviderTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupViewModelTests.swift
Labels: refactor

#61 [Feature] Localization RTL support
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/LocalizationProviderMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Provider/LocalizationProviderTests.swift
Labels: feature, task

#60 [Feature] Accessibility announcements for the CallingView
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AccessibilityProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantGridsViewModelTests.swift
Labels: feature

#29 [Feature] Supporting pinch, zoom, pan gestures and "double tap to zoom" in video screen share view in a call
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/EnvironmentValuesExtension.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/State/AppLifeCycleState.swift
  AzureCommunicationUI/AzureCommunicationUITests/Builder/ParticipantInfoModelBuilder.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantCellViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantGridsViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/AppStateReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/LifeCycleReducerTests.swift
  CHANGELOG.md
Labels: feature

#66 [Feature] Error banner introducing localization
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ErrorInfoViewModelMocking.swift
Labels: feature, task

#63 [Feature] Apply Localization to SetupView to replace hardcoded string values
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AudioDeviceType.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/JoiningCallActivityView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/JoiningCallActivityViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Drawer/AudioDevicesListViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/StringKeys.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/PreviewAreaViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/SetupControlBarViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/JoiningCallActivityViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/ViewComponents/AudioDevicesListViewModelTests.swift
Labels: feature, task

#65 [Feature] Apply Localization to CallingView to replace hardcoded string values
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeParticipantsList.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerInfoType.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/StringConstants.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/StringKeys.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/BannerTextViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/BannerInfoTypeTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/BannerTextViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantsListViewModelTests.swift
Labels: feature, task

#64 [Feature] Introduce the LobbyOverlayViewModel with localization
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/LobbyOverlayView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/LobbyOverlayViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/LocalizationProviderMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/LobbyOverlayViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/JoiningCallActivityViewModelTests.swift
Labels: feature, task

#57 [Feature] Accessibility labels for dialogs
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ConfirmLeaveOverlayView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconButtonViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/PrimaryButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/PrimaryButtonViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
Labels: feature

#67 [Feature] Accessiblity navigation
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
Labels: feature, task

#71 [Refactor] Minor code style update
  AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Navigation/NavigationRouter.swift
  AzureCommunicationUICalling/Podfile
Labels: refactor

#77 [Refactor] Minor code style update
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Navigation/NavigationRouter.swift
  AzureCommunicationUI/Podfile
Labels: refactor

#80 [Refactor] pdf to svg images update
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_call_end_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_call_end_24_filled.imageset/ic_fluent_call_end_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_call_end_24_filled.imageset/ic_fluent_call_end_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_camera_switch_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_camera_switch_24_regular.imageset/ic_fluent_camera_switch_24_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_camera_switch_24_regular.imageset/ic_fluent_camera_switch_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_clock_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_clock_24_filled.imageset/ic_fluent_clock_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_clock_24_filled.imageset/ic_fluent_clock_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_dismiss_16_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_dismiss_16_regular.imageset/ic_fluent_dismiss_16_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_dismiss_16_regular.imageset/ic_fluent_dismiss_16_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_meet_now_20_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_meet_now_20_regular.imageset/ic_fluent_meet_now_20_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_meet_now_20_regular.imageset/ic_fluent_meet_now_20_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_24_filled.imageset/ic_fluent_mic_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_filled.imageset/ic_fluent_mic_off_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_filled.imageset/ic_fluent_mic_off_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_regular.imageset/ic_fluent_mic_off_24_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_regular.imageset/ic_fluent_mic_off_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_on_24_filled.imageset/ic_fluent_mic_on_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_people_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_people_24_regular.imageset/ic_fluent_people_24_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_people_24_regular.imageset/ic_fluent_people_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_speaker_2_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_speaker_2_24_filled.imageset/ic_fluent_speaker_2_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_speaker_2_24_filled.imageset/ic_fluent_speaker_2_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_speaker_2_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_speaker_2_24_regular.imageset/ic_fluent_speaker_2_24_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_speaker_2_24_regular.imageset/ic_fluent_speaker_2_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_video_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_video_24_filled.imageset/ic_fluent_video_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_video_24_filled.imageset/ic_fluent_video_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_video_off_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_video_off_24_filled.imageset/ic_fluent_video_off_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_video_off_24_filled.imageset/ic_fluent_video_off_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_warning_24_filled.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_warning_24_filled.imageset/ic_fluent_warning_24_filled.pdf
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_warning_24_filled.imageset/ic_fluent_warning_24_filled.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_ios_arrow_left_24.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_ios_arrow_left_24.imageset/ic_fluent_ios_arrow_ltr_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_ios_arrow_left_24.imageset/ic_ios_arrow_left_24_outlined.pdf
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/IconProvider.swift
Labels: refactor

#70 [Bugfix] Force portrait mode in setup view
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/DeviceExtension.swift
  CHANGELOG.md
Labels: bug

#83 [Feature] Resolve issue where VoiceOver would sometimes read a word for an icon. Also added label for new join call button.
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButtonViewModel.swift
Labels: task

#81 [Bugfix] Solve the retain cycle between videoViewManager and Coordinate
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
Labels: bug

#85 [Refactor] Rename LocalizationKey enum and remove unused localizationProvider
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeParticipantsList.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AudioDeviceType.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerInfoType.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUITests/LocalizationProviderMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Provider/LocalizationProviderTests.swift
Labels: refactor

#82 [Bugfix] Corrected view padding in Lobby overlay view
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/LobbyOverlayView.swift
Labels: bug

#68 [FEATURE] Accessibility for Participant Header on the Calling Screen
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/DI/DependancyContainer.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeParticipantsList.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AccessibilityProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/AccessibilityProviderNotificationsObserver.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/IconAndLabelConversion.swift
  AzureCommunicationUI/AzureCommunicationUITests/AccessibilityProviderMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/BannerTextViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/BannerTextViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantGridsViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
Labels: task

#86 [FEATURE] Localize Accessibility Strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/IconAndLabelConversion.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/PrimaryButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ControlBarViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/LocalVideoViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantGridsViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/ViewComponents/LocalVideoViewModelTests.swift
  AzureCommunicationUI/Podfile.lock
Labels: task

#92 [Bug] Resolved the double tap to zoom issue in landscape mode on a device with an iOS home indicator and extended the screen share view to vertical edge of screen
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
Labels: bug

#95 [Feature] Added basic XCUITests for leave call
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
Labels: feature, task

#99 [Refactor] Renaming for some public facing API
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeEventsHandler.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeOptions.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/GroupCallOptions.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/TeamsMeetingOptions.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/CompositeErrorManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Action/CallingAction.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Middleware/CallingMiddlewareHandlerExtension.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/State/ErrorState.swift
  AzureCommunicationUI/AzureCommunicationUI/Service/Calling/CallingSDKWrapper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/CallCompositeOptions/GroupCallOptionsTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/CallCompositeOptions/TeamsMeetingOptionsTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/LocalizationProviderMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Provider/LocalizationProviderTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/AppStateReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/ErrorReducerTests.swift
  CHANGELOG.md
  docs/api/CallComposite/Reference.md
  docs/api/CallComposite/enums/LanguageCode.md
  docs/api/CallComposite/structs/CommunicationUIErrorEvent.md
  docs/api/CallComposite/structs/GroupCallOptions.md
  docs/api/CallComposite/structs/LocalizationConfiguration
  docs/api/CallComposite/structs/LocalizationConfiguration.md
  docs/api/CallComposite/structs/TeamsMeetingOptions.md
Labels: refactor

#89 [Bug] Demo App AuthenticationHelper never called back in case of error
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AuthenticationHelper.swift
Labels: bug
