Repository Azure/communication-ui-library-ios, pull requests merged in 2022-10, with the labels that each got.

#367 [Bug] Fix drawer orientation changes when device is on a flat surface
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/LockPhoneOrientation.swift
Labels: bug

#369 [Task] update pod spec source files and resources path
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: task

#368 [Doc] Added release date in CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: documentation

#360 [Bugfix] Italy Accessiblity DemoApp fix
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/it.lproj/LaunchScreen.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/it.lproj/Localizable.strings
Labels: bug

#363 [Bug] Fix Rotation does not work until drawer opens on iOS 16
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
Labels: bug

#375 [Refactor] Add Test Cases for Camera Pause
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
Labels: refactor

#377 [Feature] Basic Chat Views
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Localization/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BubbleMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageInputView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageInputViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/ThreadView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/ThreadViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TopBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TopBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ParticipantsState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ViewModels/ChatViewModelMocking.swift
Labels: task

#365 [Bugfix] Fixed timer resources deallocation when a user leaves and rejoins a call quickly
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
Labels: bug

#379 [Feature] Implemented fetch initial messages
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/DI/DependencyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/CompositeManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BubbleMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/ThreadViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/RepositoryAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatMessageExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatParticipantExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/MessageRepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/MessageRepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/RepositoryReducerTests.swift
Labels: task

#385 [Feature] Chat realtime notification for receive message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/BaseInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatEventModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ParticipantInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/UserEventTimestampModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/ThreadViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/RepositoryAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKEventsHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/RepositoryReducerTests.swift
Labels: task

#389 [Feature] Update the functionality of getCurrentDiagnosticInfo
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
Labels: task

#388 [Bug] Fix callingMiddleware unit test async running issue
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
Labels: bug

#390 [Task] Handle Chat Typing Indicator Receiving
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/UserEventTimestampModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKEventsHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
Labels: task

#386 [Task] Updated UI test to accommodate use of aad token joining a call
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift
Labels: task

#380 [Task] add a aad token for getting the acs token in joining a call
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/AuthenticationHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Info.plist
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift
Labels: task

#383 [Bugfix] Turn camera on/off when going on hold and resuming.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
Labels: bug

#391 [Feature] Implemented event handlers for service layer for Chat Composite
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatEventModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatThreadInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ParticipantsInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
Labels: task

#392 [Task] Add functionality to retrieve callId
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DiagnosticConfig.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/DiagnosticsManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/Action.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/CallingAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/NavigationReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingServiceMocking.swift
Labels: task

#397 [Feature] Implemented send message for ChatComposite
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageInputViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/ThreadViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/RepositoryAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/ChatMessageExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/RepositoryReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#396 [Task] Synced Chat views with Android and Figma
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_send_24_filled.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_fluent_send_24_filled.imageset/ic_fluent_send_24_filled.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_ios_arrow_left_24.imageset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Assets.xcassets/Icon/ic_ios_arrow_left_24.imageset/ic_fluent_ios_arrow_ltr_24_regular.svg
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/CompositeManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TopBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TopBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/FluentUI/Icon.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/ViewComponents/Button/IconButtonViewModel.swift
Labels: task

#395 [Bugfix] Added new iOS prompt handling in UI test for iOS 16
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift
Labels: bug

#401 [Task] Chat typing indicator sending - redux/service layer, PR #2 of 2
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Localization/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/LocalizationProviderMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#402 [Feature] Implemented chat message history pagination
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/RepositoryAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/RepositoryReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#407 [Documentation] Update the comment block for title argument
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
Labels: documentation

#405 [Task] Message view models and list formatting
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/MessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/SystemMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/Message/TextMessageViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
Labels: task

#408 [Feature] Implemented redux for Chat Service events
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatThreadInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/ErrorManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ErrorAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/NavigationReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/ChatCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/ErrorManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ChatReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/ErrorReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Reducer/NavigationReducerTests.swift
Labels: task

#399 [Feature] Add Chat Typing Indicator
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Localization/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/FluentUI/Wrapper/TypingParticipantAvatarGroup.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/FluentUI/Wrapper/TypingParticipantAvatarGroupContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ParticipantsState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKEventsHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/LocalizationProviderMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: feature, task

#410 [Feature] Adding new skeleton for add / remove participant event
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/AppConfig.xcconfig
  AzureCommunicationUI/Podfile.lock
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ParticipantsInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/TypingParticipantsViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/RepositoryMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ParticipantsState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/Extension/TrouterEventExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/RepositoryHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatServiceEventHandlerTests.swift
Labels: feature

#404 [Task] Send read receipt service redux layer
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatActionHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/ChatMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Service/ChatServiceTests.swift
Labels: task

#413 [Feature] Adding new unit tests for Add Participant and Remove Participant
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/MessageRepositoryManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Redux/Middleware/RepositoryMiddlewareHandlerTests.swift
Labels: feature

#414 [Bugfix] Resolved Call on Hold video issue
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
Labels: bug

#418 [Feature] Making the service call to request list of participants
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatSDKWrapperMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/ChatServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/Redux/ChatActionHandlerMocking.swift
Labels: feature
