Repository Azure/communication-ui-library-ios, pull requests merged in 2022-07, with the labels that each got.

#282 [Bugfix] Fixed the one UITest failure reported in app center about setting text in acs text field
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Info.plist
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Utilities/AccessibilityId.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoAppUITests/Info.plist
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoAppUITests/Utilities/XCUIElementExtension.swift
Labels: bug

#293 [Bugfix] Fixed issue in uitest that app is not able to fully dismiss the settings page
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppLaunchTests.swift
Labels: bug

#298 [Documentation] Update the version to GA for CallingSDK
  docs/manual-installation.md
Labels: documentation

#297 [Bugfix] Fixed Participant Drawer Height Calculation
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
Labels: bug

#296 [Bugfix] Fixed VoiceOver functionality for InfoHeaderView
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
Labels: bug

#299 [Documentation] Updated CHANGELOG
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: documentation

#295 [Bugfix] Fixed accessibility label not reflecting on hold status
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
Labels: bug

#302 [Documentation] Back merge main to develop
  README.md
  docs/manual-installation.md
Labels: refactor
