Repository Azure/communication-ui-library-ios, pull requests merged in 2022-08, with the labels that each got.

#301 [Feature] Device Manager failure throws new unknown error
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandlerExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift
Labels: feature

#304 [Refactor] Fixed Function Label Typo
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/DeviceExtension.swift
Labels: refactor

#305 [Bug] Fixed Low Contrast Ratio for On-hold Label and Drawer Icons
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/iconSecondaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/textSecondaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/ColorExtension.swift
Labels: bug

#307 optimization token fetch refresher to avoid passing in nil
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/AuthenticationHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
Labels: feature, refactor

#311 Send error to Contoso when my video start fails
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/ErrorReducerTests.swift
Labels: feature

#315 [Hotfix] Update podspec to use the info.plist from repo
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: hotfix

#313 [Feature] Link to mobile settings page for permissions
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/AccessibilityIdentifier.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
Labels: feature

#309 [Feature] Allow customizing title and subtitle
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/AvatarManagerTests.swift
Labels: feature

#316 [Feature] Show error banner when video start/stop fails
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/ErrorInfoViewModelTests.swift
Labels: feature

#308 [Bug] Fixed Text Getting Cut Off in Accessibility Mode
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
Labels: bug

#314 [Refactor] Updated App to Use FluentUI Colours
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/ACSPrimaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/backgroundColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/disabledColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/drawerColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/errorColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/gradientColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/gridLayoutBackgroundColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/iconSecondaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/mute.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/onBackgroundColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/onErrorColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/onPrimaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/onSuccessColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/onSurfaceColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/onWarningColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/popoverColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/successColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/surfaceColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/surfaceDarkColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/surfaceLightColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/textSecondaryColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Assets.xcassets/Color/warningColor.colorset/Contents.json
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeAudioDevicesListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/ColorExtension.swift
Labels: refactor

#320 [Refactor] Avatar assets update
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/cat.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/cat.imageset/cat.svg
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/cat.imageset/cat4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/cat.imageset/cat4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/cat.imageset/cat4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/cat4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/fox.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/fox.imageset/fox.svg
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/fox.imageset/fox4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/fox.imageset/fox4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/fox.imageset/fox4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/fox4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/koala.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/koala.imageset/koala.svg
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/koala.imageset/koala4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/koala.imageset/koala4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/koala.imageset/koala4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/koala4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/monkey.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/monkey.imageset/monkey.svg
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/monkey.imageset/monkey4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/monkey.imageset/monkey4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/monkey.imageset/monkey4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/monkey4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/mouse.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/mouse.imageset/mouse.svg
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/mouse.imageset/mouse4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/mouse.imageset/mouse4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/mouse.imageset/mouse4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/mouse4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/octopus.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/octopus.imageset/octopus.svg
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/octopus.imageset/octopus4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/octopus.imageset/octopus4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/octopus.imageset/octopus4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Assets.xcassets/Avatars/octopus4x.png
Labels: refactor

#321 [Bug] Updated Error Banner Colour Scheme
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/ColorThemeProvider.swift
Labels: bug

#324 [HotFix] Update podspec file
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: hotfix

#322 [Bug] refactor code for xcode13.3.1 test failure
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
Labels: bug

#318 [Refactor] Back merge main branch to developer
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: refactor
