Repository Azure/communication-ui-library-ios, pull requests merged in 2022-04, with the labels that each got.

#91 [Feature] Introduce new unit tests for error info view model
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/ErrorInfoViewModelTests.swift
Labels: feature

#94 [Feature] AppCenter Crash Logging
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AppDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Info.plist
  AzureCommunicationUI/AzureCommunicationUIDemoApp/SceneDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
Labels: task

#104 [Documentation] Update for 1.0.0-beta.2 release
  AzureCommunicationUI.podspec
  AzureCommunicationUI/AzureCommunicationUI/Info.plist
  AzureCommunicationUI/AzureCommunicationUITests/CallCompositeOptions/DiagnosticConfigTests.swift
  CHANGELOG.md
  README.md
Labels: documentation

#113 [Documentation] Podspec update
  AzureCommunicationUI.podspec
Labels: documentation

#116 [Refactor] Back-merge main to develop
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/ISSUE_TEMPLATE/request-a-feature.md
  AzureCommunicationUI.podspec
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/Info.plist
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ConfirmLeaveOverlayView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/VideoView/VideoRenderView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
  AzureCommunicationUI/AzureCommunicationUITests/CallCompositeOptions/DiagnosticConfigTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Provider/LocalizationProviderTests.swift
  CHANGELOG.md
  README.md
Labels: refactor

#52 [Feature] Theming Tint Options
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/ThemeConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/ColorExtension.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/ThemeConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
Labels: feature, task

#119 [BugFix] Update disabled color for buttons
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Color/disabledColor.colorset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Color/onDisabledColor.colorset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
Labels: bug

#96 [Refactor] Add tests for InfoHeaderViewModelTest, ControlBarViewModel and ParticipantsListViewModel
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Drawer/AudioDevicesListViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/IconButtonViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantsListViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantsListViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/ViewComponents/AudioDevicesListViewModelTests.swift
Labels: refactor

#109 [Bugfix] Resolved issue where waiting host message was not correctly read by voice over.
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/LobbyOverlayView.swift
Labels: bug

#103 [Feature] Bumping minimum target to iOS 14
  AzureCommunicationUI.podspec
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ConfirmLeaveOverlayView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/PrimaryButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/ViewModifier/TextFieldClearButton.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
  AzureCommunicationUI/Podfile
  CHANGELOG.md
Labels: feature

#120 [Feature] Introduce a skeleton AvatarManager
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CommunicationULocalDataOptions.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AvatarManager.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/AvatarManagerTests.swift
Labels: task

#127 [Documentation] Updating CHANGELOG with missing content
  CHANGELOG.md
Labels: documentation

#124 [Documentation] Include URL format for EnvConfig in Demo ReadMe
  AzureCommunicationUI/AzureCommunicationUIDemoApp/README.md
  docs/images/EnvConfig.png
Labels: documentation

#90 [Feature] Added XCUITest for join call and leave call related UX
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ConfirmLeaveOverlayView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/ViewModifier/TextFieldClearButton.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUIElementExtension.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
Labels: feature

#107 [Bugfix] Added a work-around is to make sure the setup view rotates back to portrait if the previous screen was on a different orientation.
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/DeviceExtension.swift
Labels: bug

#122 [Bugfix] Fix accessibility for localVideoFullscreenView
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
Labels: bug

#121 [Feature] Theming Tint Options
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/ThemeConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/ColorThemeProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/ColorExtension.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/ThemeConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/Podfile.lock
Labels: feature

#130 [Bugfix] Fix accessibility for the CallingView
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/AccessibilityProviderNotificationsObserver.swift
Labels: bug

#128 [BugFix] Fix the issue that iphone pro max doesn't show screen share in landscape mode
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/DeviceExtension.swift
  CHANGELOG.md
Labels: bug

#131 [Feature] Implement the Local Avatar into Composite
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallComposite.swift
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CommunicationULocalDataOptions.swift
  AzureCommunicationUI/AzureCommunicationUI/DI/DependancyContainer.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Factories/CompositeViewFactory.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/cat.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/cat.imageset/cat4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/cat.imageset/cat4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/cat.imageset/cat4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/cat4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/fox.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/fox.imageset/fox4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/fox.imageset/fox4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/fox.imageset/fox4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/fox4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/koala.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/koala.imageset/koala4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/koala.imageset/koala4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/koala.imageset/koala4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/koala4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/monkey.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/monkey.imageset/monkey4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/monkey.imageset/monkey4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/monkey.imageset/monkey4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/monkey4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/mouse.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/mouse.imageset/mouse4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/mouse.imageset/mouse4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/mouse.imageset/mouse4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/mouse4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/octopus.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/octopus.imageset/octopus4x-1.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/octopus.imageset/octopus4x-2.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/octopus.imageset/octopus4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Assets.xcassets/Avatars/octopus4x.png
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AuthenticationHelper.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/AvatarManagerTests.swift
  CHANGELOG.md
Labels: feature

#129 [Feature] added leave call confirmation drawer list
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_call_end_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_call_end_24_regular.imageset/ic_fluent_call_end_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationList.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeLeaveCallConfirmationListCell.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ConfirmLeaveOverlayView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Drawer/LeaveCallConfirmationViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/ViewModifier/TextFieldClearButton.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ControlBarViewModelTests.swift
  CHANGELOG.md
Labels: feature

#123 [Bugfix] Added icon for unmuted state in participant view and resolved accessibility issue where VoiceOver did not indicate particpants correctly.
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_24_regular.imageset/ic_fluent_mic_24_regular.svg
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/Podfile.lock
Labels: bug

#133 [Feature] Added localization support for ll and ll-CC format
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/es-ES.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ja-JP.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hans-CN.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hant-TW.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
Labels: feature

#126 [Feature] Localization: auto OS language detection
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/fr-CA.lproj/LaunchScreen.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/fr-CA.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/fr.lproj/LaunchScreen.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/fr.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/zh-Hant.lproj/LaunchScreen.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/zh-Hant.lproj/Localizable.strings
Labels: feature

#132 [Feature] Ability to drag pip and keep it within bounds of container
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/Podfile.lock
Labels: task

#135 [Bug] Remove duplicate file reference for AvatarManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
Labels: bug

#137 [Documentation] Update CHANGELOG with localization features
  CHANGELOG.md
Labels: documentation

#136 [Feature] App Centre Crash Logging
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AppDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Info.plist
  AzureCommunicationUI/AzureCommunicationUIDemoApp/SceneDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
Labels: feature

#139 [Feature] Call Eviction
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CommunicationUIErrorEvent.swift
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Service/Calling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/ErrorReducerTests.swift
Labels: feature

#145 [Refactor] Back Merge Branch Main
  README.md
  docs/api/CallComposite/Reference.md
  docs/api/CallComposite/classes/CallComposite.md
  docs/api/CallComposite/enums/LanguageCode.md
  docs/api/CallComposite/protocols/ThemeConfiguration.md
  docs/api/CallComposite/structs/CallCompositeErrorCode.md
  docs/api/CallComposite/structs/CallCompositeOptions.md
  docs/api/CallComposite/structs/CommunicationUIErrorEvent.md
  docs/api/CallComposite/structs/GroupCallOptions.md
  docs/api/CallComposite/structs/LocalizationConfiguration.md
  docs/api/CallComposite/structs/TeamsMeetingOptions.md
Labels: refactor

#146 [Refactor] Localization key prefix rename
  AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
  AzureCommunicationUI/AzureCommunicationUI/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/es-ES.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ja-JP.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hans-CN.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hant-TW.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Localization/zh.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUI/Utilities/LocalizationKey.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/fr-CA.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/fr.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/BannerTextViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/LobbyOverlayViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/JoiningCallActivityViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
Labels: refactor

#144 [Bugfix] Removed the related UITests on control views in setup screen
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITestsLaunchTests.swift
Labels: bug

#138 [Feature] Calculate initial PIP position correctly based on orientation
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/Podfile.lock
Labels: task

#150 [Refactor] Improved accessibility and UITest for leave call drawer, also cleaned up unneeded UITests
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Drawer/LeaveCallConfirmationViewModel.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ControlBarViewModelTests.swift
Labels: refactor
