Repository Azure/communication-ui-library-ios, pull requests merged in 2022-09, with the labels that each got.

#328 [Feature] Add Alert When Network Lost
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/NetworkManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/SetupViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
Labels: feature

#330 [Refactor] Made Title Required in LocalOptions
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
Labels: refactor

#334 [Task] Change unknownError to cameraFailure error
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift
Labels: task

#336 [Refactoring]Td translation for go to settings and camera on error message
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh.lproj/Localizable.strings
Labels: task

#335 [Refactoring] TDBuild - updating localized resource files.
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es-ES.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja-JP.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans-CN.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant-TW.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh.lproj/Localizable.strings
Labels: task

#329 [Refactor] Coding Style updates for Constants
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
Labels: refactor

#332 [Refactor] Update CHANGELOG for Release Branch
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
Labels: refactor

#337 [Task] Increment project version for release
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
Labels: task

#331 [Bug] Info Header Font Size Fix
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
Labels: bug

#342 [Refactor] Updated Remote Manager to Protocol
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/DI/DependencyContainerTests.swift
Labels: refactor

#345 [Bug] Accessiblity bug fixes for Italy accessibility compliance
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeAudioDevicesListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
Labels: bug

#338 [Task] Update podSpec
  AzureCommunicationUI/sdk/AzureCommunicationUICalling.podspec
Labels: task

#348 [Bug] Video Going Blank After Returning to Foreground
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
Labels: bug

#341 [Doc] Update README
  README.md
Labels: refactor

#354 [Bugfix] Drawers dynamic update fix
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
Labels: bug

#333 [Feature] Feature/refactor icon with label button to be mulit state toggle
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/ButtonState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButtonViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/IconWithLabelButtonViewModelMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/SetupControlBarViewModelTests.swift
Labels: feature

#356 [Refactor] Use protocol of avatarViewManager and decouple it with localOption
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AvatarViewManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/RemoteParticipantsManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/DraggableLocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/ParticipantGridLayoutView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/AvatarManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/RemoteParticipantsManagerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ParticipantsListViewModelTests.swift
Labels: refactor

#355 [Refactor] Backmerge a few commit from develop branch
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/DI/DependancyContainer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeAudioDevicesListCell.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/DrawerContainerViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/DI/DependencyContainerTests.swift
Labels: bug

#353 [Bugfix] Join call button accessiblity text sizing fix
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeButton.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/FontExtension.swift
Labels: bug

#351 [Refactor] Rename Navigation Bar View Data
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
Labels: refactor

#344 [Refactor] refactor xc test setup into factory method
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/BannerTextViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/BannerViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/LobbyOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/OnHoldOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ParticipantsListViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Provider/LocalizationProviderTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/ErrorInfoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/JoiningCallActivityViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/ViewComponents/LocalVideoViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/AudioSessionReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/ErrorReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/LifeCycleReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/LocalUserReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/NavigationReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/PermissionReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallingServiceTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/NavigationRouterTests.swift
Labels: task

#346 [Feature][Chat] Added skeleton structure for chat redux
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/DiagnosticConfig.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ParticipantInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/Action.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ChatAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ErrorAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Action/ParticipantsAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceEventHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatServiceListener.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/MessageRepositoryMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/MessareRepositoryHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/AppStateReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ChatReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/LifeCycleReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/NavigationReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ParticipantsReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/AppState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ChatState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/ErrorState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/State/NavigationState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKEventsHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapper.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatSDKWrapperProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Service/Chat/ChatService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/ChatCompositeInternalError.swift
Labels: task

#358 [Doc] Readme and Changelog Update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  README.md
Labels: documentation

#352 [Feature] Remove local user from participant list when the app will be terminated
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AppLifeCycleManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/CallingAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/LifecycleAction.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddleware.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/LifeCycleReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/NavigationReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/AppLifeCycleState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallingMiddlewareHandlerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Reducer/LifeCycleReducerTests.swift
Labels: feature

#366 [Bug] Error Banner Margin Fix
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift
Labels: bug, refactor
