Repository Azure/communication-ui-library-ios, pull requests merged in 2022-02, with the labels that each got.

#36 [Bugfix] Updated the participant list UIs to match the latest UX requirement and Android for consistency
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Color/mute.colorset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_regular.imageset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Icon/ic_fluent_mic_off_24_regular.imageset/ic_fluent_mic_off_24_regular.pdf
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeParticipantsListCell.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/Style/IconProvider.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListCellViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Utilities/StringConstants.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantsListViewModelTests.swift
Labels: bug

#40 [Documentation] Readme updates for participant list UX bug fixes
  CHANGELOG.md
Labels: documentation, feature

#41 [Refactor] Info.plist clean up
  AzureCommunicationUI/AzureCommunicationUI/Info.plist
Labels: refactor

#43 [Refactor] Apply SwiftLint to unit tests and demo app
  AzureCommunicationUI/.swiftlint.yml
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/.swiftlint.yml
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AppDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/EnvConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/SceneDelegate.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/ThemeConfig.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Utilities/Extension.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/CustomControls.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/.swiftlint.yml
  AzureCommunicationUI/AzureCommunicationUITests/CallCompositeOptions/DiagnosticConfigTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/CallingMiddlewareHandlerMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/DI/DependencyContainerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/CallingSDKWrapperMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/PermissionsManagerMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/BannerTextViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/InfoHeaderViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantCellViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantGridsViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantsListViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Factories/CompositeViewModelFactoryTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/PreviewAreaViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/ViewComponents/AudioDeviceListViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/ViewComponents/LocalVideoViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Middleware/CallingMiddlewareTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/AppStateReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/ErrorReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/LifeCycleReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/LocalUserReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/NavigationReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/PermissionReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Service/CallingServiceTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Service/NavigationRouterTests.swift
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
Labels: refactor

#49 [Refactor] Update FluentUI version to 0.3.9
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
  CHANGELOG.md
Labels: refactor

#50 [Bugfix] Fix the title view appearance for unnamed users
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
Labels: bug

#44 [Feature] Joining Experience
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Color/onBackgroundColor.colorset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Assets.xcassets/Color/onSurfaceColor.colorset/Contents.json
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/JoiningCallActivityView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Action/CallingAction.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Middleware/CallingMiddlewareErrorHandler.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Middleware/CallingMiddlewareHandler.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Middleware/CallingMiddlewareHandlerExtension.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Reducer/AppStateReducer.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Reducer/CallingReducer.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/Reducer/NavigationReducer.swift
  AzureCommunicationUI/AzureCommunicationUI/Redux/State/ErrorState.swift
  AzureCommunicationUI/AzureCommunicationUI/Service/Calling/CallingSDKEventsHandler.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/SwiftUIDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Views/UIKitDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Manager/CompositeErrorManagerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupControlBarViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Setup/SetupViewModelTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/AppStateReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/CallingReducerTests.swift
  AzureCommunicationUI/AzureCommunicationUITests/Redux/Reducer/ErrorReducerTests.swift
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
  CHANGELOG.md
Labels: feature

#48 [Refactor] Add unit tests for ParticipantGridViewModel
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/BannerTextViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridCellViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/ParticipantGridsViewModelTests.swift
Labels: refactor

#53 [Bug] Fix the local pip view not showing the video stream
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
Labels: bug

#45 [Feature] Accessibility labels for Setup and Calling screens
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUI/Presentation/FluentUI/Wrapper/CompositeAvatar.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Setup/SetupViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Utilities/IconAndLabelConversion.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconButtonViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButtonViewModel.swift
  AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoViewModel.swift
Labels: feature

#51 [Refactor] Add unit tests for CallingViewModel
  AzureCommunicationUI/AzureCommunicationUI.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUITests/CompositeViewModelFactoryMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/BannerViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ControlBarViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/LocalVideoViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Mocking/ViewModels/ParticipantGridViewModelMocking.swift
  AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/CallingViewModelTests.swift
Labels: refactor
