Repository Azure/communication-ui-library-ios, pull requests merged in 2023-01, with the labels that each got.

#562 [Refactor] UI tests refactor
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Utilities/AccessibilityId.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/FloatingUITestWindow.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppCallTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppDebugInfoTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppE2ETests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppLaunchTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppPIPTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppSetupViewTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppTokenTests.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCTestCaseExtension.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUIElementExtension.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/OnHoldOverlayViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/AccessibilityIdentifier.swift
  eng/pipelines/jobs/appcenter-test-job-steps.yml
  eng/pipelines/jobs/templates/retrieve-acs-token.yml
  eng/pipelines/nightly.yml
Labels: refactor

#566 [Doc] Updated Chat version to 1.0.0
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
Labels: documentation

#575 [Bugfix] Fixed Issue Where Input Box Not Shown Up in iOS 14
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
Labels: bug

#577 [Bugfix] Resolved issue with message input box margin and send button alignment.
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
Labels: bug

#576 [Bugfix] Chat View Margin Fix
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
Labels: bug

#586 [Bugfix] Revert padding for bottom to account for older iphone
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
Labels: bug

#588 [Feature] Sending Errors up via event handler
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatDemoViewController.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Middleware/ChatActionHandler.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/ErrorReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Utilities/ChatCompositeInternalError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/ErrorManagerTests.swift
Labels: feature

#584 [Bugfix] Chat duplicate system message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Model/ChatMessageInfoModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/MessageRepositoryManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Manager/MessageRepositoryManagerTests.swift
Labels: bug

#585 [Bugfix] Fix crash on dispatch function of sendReadReceipt
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
Labels: bug

#572 [Bugfix] Fix send read receipt
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Redux/Reducer/RepositoryReducer.swift
Labels: bug

#581 [Bugfix] Fix crash on scrollToId
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListView.swift
Labels: bug

#589 [Refactor] Extract localization common functionality
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/SupportedLocale.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/LocalizationProviderMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/OnHoldOverlayViewModelTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/SupportedLocale.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/LocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/Mocking/LocalizationProviderMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/BaseLocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/LocalizationOptions.swift
Labels: refactor

#590 [Bugfix] Padding fix for message
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatView.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/BottomBarView.swift
Labels: bug

#591 [Refactor] Final UI tests updates
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKEventsHandlerMocking.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/FloatingUITestWindow.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppSetupViewTests.swift
  eng/pipelines/jobs/templates/set-appcenter-devices.yml
Labels: refactor

#592 [Task] Update PodSpec and Chat Version
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/ChatCompositeOptions/DiagnosticConfigTests.swift
Labels: task

#594 [Refactor] Remove unused file
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/common/Chat/Sources/CompositeOptions/LocalOptions.swift
Labels: refactor

#593 [Feature] Added Chat Composite Support to Release Script
  scripts/README.md
  scripts/main-repo-updater.py
Labels: bug, feature

#587 [Doc] Readme Update
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
  CHANGELOG.md
  README.md
  scripts/README.md
Labels: documentation

#595 [Bugfix] Setup UI test fix
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppSetupViewTests.swift
Labels: bug

#599 [HotFix] Make ThemeOptions internal access only
  AzureCommunicationUI/sdk/common/Core/Sources/CompositeOptions/ThemeOptions.swift
Labels: hotfix

#602 [Refactor] Common code extraction
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/BaseLocalizationProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalizationOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/AppPhaseKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/ViewExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/BaseLocalizationProviderProtocol.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/LocalizationOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ThemeOptions.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/FluentUI/Icon.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Manager/AppLifeCycleManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/Style/StyleProvider.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Button/IconButton.swift
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Button/IconButtonViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/EnvironmentValuesExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/OrientationManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/PreferenceKey.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/UIViewControllerExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/UIWindowExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/ViewExtension.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICommon/Sources/AzureCommunicationUICommon/ViewModifer.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/Utilities/EnvironmentValuesExtension.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/Utilities/OrientationManager.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/Utilities/PreferenceKey.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Presentation/SwiftUI/Utilities/ViewModifer.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Utilities/UIViewControllerExtension.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Sources/Utilities/UIWindowExtension.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Tests/Mocking/LoggerMocking.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Tests/Mocking/Redux/MiddlewareMocking.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Tests/Mocking/Redux/ReducerMocking.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Tests/Mocking/Redux/StoreFactoryMocking.swift
  AzureCommunicationUI/sdk/common/BaseComposite/Tests/Presentation/Provider/LocalizationProviderTests.swift
  AzureCommunicationUI/sdk/common/Core/Tests/CompositeOptions/DiagnosticConfigTests.swift
Labels: refactor

#603 [Documentation] Update Calling Banner image
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
  docs/images/mobile-ui-library-calling-hero-image.png
Labels: task

#601 [Documentation] Hard Coded Images for API Doc
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
  README.md
Labels: bug, hotfix

#604 [Documentation] Chat Version Update
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/ChatCompositeOptions/DiagnosticConfigTests.swift
Labels: task

#607 [Documentation] Updated Changelog for Chat Beta 2 release
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
Labels: documentation

#600 [Feature] added release script for cocoapod + improvement
  scripts/README.md
  scripts/composite.py
  scripts/main-repo-updater.py
  scripts/podspec-updater.py
Labels: feature

#608 [Documentation] Added Release Date and Tag
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
Labels: documentation
