Repository Azure/communication-ui-library-ios, pull requests merged in 2023-03, with the labels that each got.

#610 [Feature][Calling][CSS] Call history
  AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewModel.swift
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
  AzureCommunicationUI/Podfile.lock
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallHistoryRecord.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DebugInfo.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/DebugInfoManager.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SharingActivity/DebugInfoSharingActivityViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallHistoryService.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallHistoryRepositoryMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallHistoryServiceMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/DebugInfoManagerMocking.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryRepositoryTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryRepositoryTests.swift.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryServiceTests.swift
  eng/pipelines/nightly.yml
Labels: feature

#623 Update Calling UI library version to 1.2.0
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryRepositoryTests.swift.plist
Labels: feature

#633 [Bugfix] Fix version of Fluent UI for manual install documentation
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/manual-installation.md
Labels: bug

#634 Handle offline for skip setup screen
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeError.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LoadingOverlayViewModel.swift
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift
Labels: feature

#636 [Calling][Bugfix] UI test
  AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
Labels: bug

#638 [Documentation] Updated dependency versions for AzureCommunicationUIChat
  AzureCommunicationUI/Podfile
  AzureCommunicationUI/Podfile.lock
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
Labels: documentation

#646 [Chat][Documentation] AzureCommunicationUIChat 1.0.0 beta.3 documentation update
  AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
Labels: documentation
