Repository Azure/communication-ui-library-ios, pull requests merged in 2023-02, with the labels that each got.

#615 [Documentation] Update documentation on setup and run on repo
  AzureCommunicationUI/AzureCommunicationUIDemoApp/README.md
  docs/contributing-guide.md
Labels: task

#620 [Feature] Added Jazzy Pipeline for API Docs
  eng/jazzy/AzureCommunicationUICalling.yml
  eng/jazzy/AzureCommunicationUIChat.yml
  eng/pipelines/jazzy-docs.yml
  eng/pipelines/jobs/templates/jazzy-build-script.yml
Labels: feature

#622 [Bugfix] Fix inconsistency for ellipsis character
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko-KR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
  AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr.lproj/Localizable.strings
Labels: bug, task
